version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: deliverydb
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_DSN=host=db user=demo password=demo dbname=deliverydb port=5432 sslmode=disable
      - REDIS_ADDR=redis:6379
      - JWT_SECRET=supersecretkey
    ports:
      - "8080:8080"
volumes:
  db_data:
